"""
1. Covasim simulates the state of individual people, known as agents, over a number of discrete time steps. Conceptually, the model is largely focused on a single type of calculation: the probability that a given agent on a given time step will change from one state to another, such as from susceptible to infected, or from critically ill to dead. Once these probabilities have been calculated, a pseudorandom number generator with a user-specified seed is used to determine whether the transition actually takes place for a given model run.
The logical flow of a single Covasim run is as follows. First, the simulation object is created, then the parameters are loaded and validated for internal consistency, and any specified data files are loaded (described in Section 2.6.1). Second, a population of agents is created, including age, sex, and comorbidities for each agent, drawing from location-specific data distributions where available; then, agents are then connected into contact networks based on their age and other statistical properties (Section 2.4). Next, the integration loop begins. On each timestep (which corresponds to a single day by default), the order of operations is: dynamic rescaling (Section 2.6.2); applying health system constraints (Section 2.6.3); updating the state of each agent, including disease progression (Section 2.2); importation events (Section 2.6.4); applying interventions (Section 2.5); calculating disease transmission events across each infectious agent’s contact network (Section 2.3); collating outputs into results arrays (Section 2.6.5); and applying analyzers (Section 2.6.7). The following sections describe each step in more detail.
2. Diabetes. To the best of our knowledge, agent-based modeling has only been applied to the study of diabetic retinopathy (22,23). However, we believe that it can also be useful to study the progression of other diabetic complications — nephropathy, neuropathy, myocardial infarction, and stroke. In addition, future agent-based models should incorporate health behaviors, such as diet, physical activity, and smoking, and examine the impact of modifying behaviors on the prevention and management of diabetes. Finally, agent-based modeling should take into account the impact of comorbidities (eg, obesity, hypertension, hyperlipidemia) and pharmacologic interventions on the health outcomes of a person with diabetes.
Cardiovascular disease. Although the model in the study by Li et al demonstrated the possibility of using an agent-based model to study cardiovascular disease, the model has some limitations related to its design and structure (27). For example, a person is either of normal weight or overweight in the model, and detailed changes in BMI are not modeled. We believe that an agent-based model of cardiovascular disease with more detailed disease progression and validated model prediction will provide potential users with more precise insights and more confidence in using the results to inform decision-making. In addition, we suggest incorporating social influence in future modeling when studying the impact of lifestyle interventions on cardiovascular disease. Finally, future agent-based models of cardiovascular disease could take into account the effects of different treatment strategies, drug therapies, and procedures (eg, revascularization, pacemaker implantation) to improve their clinical relevance.
"""
#3.
"""
4. Diabetes. To the best of our knowledge, agent-based modeling has only been applied to the study of diabetic retinopathy (22,23). However, we believe that it can also be useful to study the progression of other diabetic complications — nephropathy, neuropathy, myocardial infarction, and stroke. In addition, future agent-based models should incorporate health behaviors, such as diet, physical activity, and smoking, and examine the impact of modifying behaviors on the prevention and management of diabetes. Finally, agent-based modeling should take into account the impact of comorbidities (eg, obesity, hypertension, hyperlipidemia) and pharmacologic interventions on the health outcomes of a person with diabetes.
Cardiovascular disease. Although the model in the study by Li et al demonstrated the possibility of using an agent-based model to study cardiovascular disease, the model has some limitations related to its design and structure (27). For example, a person is either of normal weight or overweight in the model, and detailed changes in BMI are not modeled. We believe that an agent-based model of cardiovascular disease with more detailed disease progression and validated model prediction will provide potential users with more precise insights and more confidence in using the results to inform decision-making. In addition, we suggest incorporating social influence in future modeling when studying the impact of lifestyle interventions on cardiovascular disease. Finally, future agent-based models of cardiovascular disease could take into account the effects of different treatment strategies, drug therapies, and procedures (eg, revascularization, pacemaker implantation) to improve their clinical relevance.
5. stay as group, form a triangle so that wind resistanced is low. Boids
"""
